# Generated by Django 5.1.2 on 2024-10-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_image_blogpost_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='read_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='BlogPostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
