# Generated by Django 5.1.2 on 2024-10-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpostimage_image_title_blogpostimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostimage',
            name='image_title',
        ),
        migrations.RemoveField(
            model_name='blogpostimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
