# Generated by Django 5.1.2 on 2024-10-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpostimage_image_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostsection',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
