# Generated by Django 5.1.2 on 2024-10-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostsection',
            name='math_content',
            field=models.TextField(blank=True, help_text='Enter LaTeX-formatted math content', null=True),
        ),
    ]
