# Generated by Django 5.1.2 on 2024-11-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpostsection_math_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostsection',
            name='content',
            field=models.TextField(help_text='Add content with embedded math formulas and code snippets.'),
        ),
    ]
