# Generated by Django 5.1.2 on 2024-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpostsection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostsection',
            name='content',
            field=models.TextField(),
        ),
    ]
