# Generated by Django 5.1.2 on 2024-11-01 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpostsection_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostsection',
            name='code',
        ),
        migrations.RemoveField(
            model_name='blogpostsection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpostsection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpostsection',
            name='image_title',
        ),
        migrations.RemoveField(
            model_name='blogpostsection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='blogpostsection',
            name='math_content',
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('math', 'Math'), ('code', 'Code'), ('image', 'Image')], max_length=10)),
                ('content', models.TextField(blank=True, help_text='Enter text or LaTeX for math content.', null=True)),
                ('code', models.TextField(blank=True, help_text='Enter code snippet if content type is code.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image if content type is image.', null=True, upload_to='blog_images/')),
                ('image_title', models.CharField(blank=True, help_text='Optional title for the image.', max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='blog.blogpostsection')),
            ],
        ),
    ]
