# Generated by Django 5.1.2 on 2024-11-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogpostsection_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image_url',
            field=models.URLField(blank=True, help_text='Enter URL for an external image if content type is image.', null=True),
        ),
    ]
